spring:
  datasource:
    url: jdbc:mysql://localhost:3306/physical_examination?characterEncoding=utf-8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

server:
  port: 9090

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

logging:
  level:
    com.example.backend.mapper: debug